version: '3.1'

services:
  # mysql:
  #   image: mysql:8.0.32
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "admin"
  #     MYSQL_DATABASE: "test"
  #   volumes:
  #     - ~/datalocal/mysql_data:/var/lib/mysql
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - devlocal
  
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ~/datalocal/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - devlocal
  
  redis:
    image: redis:6.2.6-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ~/datalocal/redis:/data
    ports:
      - "6379:6379"
    networks:
      - devlocal

  # elasticsearch:
  #   image: elasticsearch:7.16.3
  #   ports: 
  #    - "9200:9200"
  #   env_file:
  #     - ~/elasticsearch-data/elasticsearch.env
  #   volumes:
  #     - ~/elasticsearch-data:/usr/share/elasticsearch/data
  # kibana:
  #   image: kibana:7.16.3
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
  # adminer:
  #   image: adminer:4.8.1-standalone
  #   restart: always
  #   ports:
  #     - 8080:8080

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: pma
  #   links:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 8082:80

  pgadmin4:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ~/datalocal/pgadmin:/var/lib/pgadmin
    ports:
      - 53603:53603
      - 8081:80
    networks:
      - devlocal

networks:
  devlocal:
