version: '3.1'

services:
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.6-alpine
    restart: always
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080