version: '3.1'

services:
  elasticmq:
    image: softwaremill/elasticmq-native:1.5.7
    volumes:
      - /Volumes/Working/datalocal/elasticmq/elasticmq.conf:/opt/elasticmq.conf
    ports:
      - 9324:9324
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /Volumes/Working/datalocal/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - devlocal
  redis:
    image: redis:7.0.11-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - /Volumes/Working/datalocal/redis:/data
    ports:
      - "6379:6379"
    networks:
      - devlocal
  pgadmin4:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@codingland.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /Volumes/Working/datalocal/pgadmin:/var/lib/pgadmin
    ports:
      - 53603:53603
      - 8081:80
    networks:
      - devlocal
  hasura:
    image: hasura/graphql-engine:v2.17.1
    networks:
      - devlocal
    ports:
      - "8083:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Volumes/Working/datalocal/hasura:/conf
    env_file: .env

networks:
  devlocal:

